### PR TITLE
Removed rules that are deprecated in Stylelint 8.0.

### PR DESCRIPTION
**Pull request by keeganstreet**

### CODE REVIEW

**Comment by jennasalau** [comment]
Should we update the package json Stylelint dev dependency to `^8.0.0` too?

**Comment by keeganstreet** [comment]
Not yet, it hasn't been released yet. I just want to stop seeing deprecation warnings for now.

**Comment by jennasalau** [comment]
Hey @keeganstreet I've merged. Feel free to bump the patch number and publish to NPM.

**Comment by keeganstreet** [comment]
Thanks. I've published to npm.

**Pull request merged**
